# Generated by Django 3.1.5 on 2021-02-03 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bikerental', '0001_initial'),
        ('dealer', '0001_initial'),
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='bike_location',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bikerental.location'),
        ),
        migrations.AddField(
            model_name='bike',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.dealer'),
        ),
    ]
