# Generated by Django 3.1.5 on 2021-02-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0003_bike_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='dropodd_add',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='bike',
            name='is_on_halt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bike',
            name='pickup_add',
            field=models.TextField(default=''),
        ),
    ]
