# Generated by Django 3.1.5 on 2021-02-04 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0004_auto_20210204_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='dropodd_add',
            new_name='dropoff_add',
        ),
    ]
