# Generated by Django 3.1.5 on 2021-02-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0006_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='dropoff_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_date',
            field=models.DateTimeField(),
        ),
    ]
