# Generated by Django 3.1.5 on 2021-02-19 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0007_auto_20210218_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='bike_id',
            new_name='bike',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
