# Generated by Django 3.1.5 on 2021-02-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0009_booking_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='dropoff_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_date',
            field=models.DateField(),
        ),
    ]
