# Generated by Django 3.1.5 on 2021-02-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0010_auto_20210219_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_rent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
