# Generated by Django 3.1.5 on 2021-02-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikerental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
