# Generated by Django 3.1.5 on 2021-02-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikerental', '0002_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
