# Generated by Django 3.1.5 on 2021-02-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerprofile',
            name='profile_pic',
            field=models.ImageField(default='default.jpg', upload_to='dealer_profile_pics'),
        ),
    ]
